version: "3.9"
   
services:
  web:
    build: .
    container_name: hello
    command: flask run --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=hello